files:
  - source: /apps/aiao.io/content/zh/**/*.md
    translation: /apps/aiao.io/content/%two_letters_code%/**/%original_file_name%
  - source: /apps/aiao.io/src/locales/zh-Hans.xlf
    translation: /apps/aiao.io/src/locales/%two_letters_code%.%file_extension%
  - source: /README.md
    translation: /%file_name%-%two_letters_code%.%file_extension%
